# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Remove this after
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/15bede60-8654-4fd7-aeea-b003cb0e99c6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0EAC-803D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # nvme
  fileSystems."/mnt/nvme" = 
    { device = "/dev/disk/by-uuid/01DC63042C7BC480";
      fsType = "ntfs";
      options = [ "rw" "uid=1000"];
    };

  # ssd
  fileSystems."/mnt/ssd" = 
    { device = "/dev/disk/by-uuid/44e264e5-07e3-49ec-8345-7002973c4e3e";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fdadfbb9-ceb6-4131-857b-01cffb61c150"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
